server:
  port: 8100

spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: demo_user
    password: demo_pass
    driver-class-name: com.mysql.jdbc.Driver

endpoints:
  health:
    sensitive: false
  shutdown:
    enabled: true